### ISSUE TITLE
Failed to receive all messages from multiple clients in the iot end-to-end example

### ISSUE THREAD

**Issue by KKKKKyle** [GoogleCloudPlatform/python-docs-samples#4163] opened 2020-06-25 04:51 UTC
## In which file did you encounter the issue?

python-docs-samples/iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py

### Did you change the file? If so, how?

No

## Describe the issue

I run two clients (run python cloudiot_pubsub_example_mqtt_device.py in two terminals) almost at the same time to simulate two iot clients sending data to the server which was "listening". It supposed to be 5 * 2 messages in total that the server would receive. However, the total number of messages that the server actually received was only 7. I run all three scripts locally on my mac. I noticed that in the codes' comments, the thread-safety issue is mentioned. I'm wondering if it's related. Or, this is expected with cloud computing. The whole output is attached below.

**Client1**
```
python cloudiot_pubsub_example_mqtt_device.py     --project_id=testiot-280418     --registry_id=my-registry     --device_id=kit_cam     --private_key_file=rsa_private2.pem     --mqtt_bridge_port=443     --cloud_region=us-central1     --algorithm=RS256     --num_messages=5
Creating JWT using RS256 from private key file rsa_private2.pem
Connection Result: 0: No error.
Publishing payload {"temperature": 1}
Subscribed:  (1,)
Received message '""' on topic '/devices/kit_cam/config' with Qos 1
Received message '""' on topic '/devices/kit_cam/config' with Qos 1
Published message acked.
Publishing payload {"temperature": 2}
Published message acked.
Publishing payload {"temperature": 3}
Published message acked.
Publishing payload {"temperature": 4}
Published message acked.
Publishing payload {"temperature": 5}
Published message acked.
Disconnected: 0: No error.
Finished loop successfully. Goodbye!
```

**Client2**
```
python cloudiot_pubsub_example_mqtt_device.py     --project_id=testiot-280418     --registry_id=my-registry     --device_id=din_cam     --private_key_file=rsa_private.pem     --mqtt_bridge_port=443     --cloud_region=us-central1     --algorithm=RS256     --num_messages=5
Creating JWT using RS256 from private key file rsa_private.pem
Connection Result: 0: No error.
Publishing payload {"temperature": 1}
Subscribed:  (1,)
Received message '""' on topic '/devices/din_cam/config' with Qos 1
Received message '""' on topic '/devices/din_cam/config' with Qos 1
Published message acked.
Publishing payload {"temperature": 2}
Published message acked.
Publishing payload {"temperature": 3}
Published message acked.
Publishing payload {"temperature": 4}
Published message acked.
Publishing payload {"temperature": 5}
Published message acked.
Disconnected: 0: No error.
Finished loop successfully. Goodbye!
```

**Server**
```
python cloudiot_pubsub_example_server.py  --project_id=testiot-280418  --pubsub_subscription=my-subscription  --service_account_json="./service_account.json"
Listening for messages on projects/testiot-280418/subscriptions/my-subscription
The device (kit_cam) output is: 1
The device (kit_cam) output is: 2
The device (kit_cam) output is: 3
The device (din_cam) output is: 4
The device (kit_cam) output is: 4
The device (din_cam) output is: 5
The device (kit_cam) output is: 5
```

**Comment by gguuss** [comment] 2020-08-05 17:04
The thread safety issue is for the modify cloud config calls and should not affect the ability of the sample to accurately receive and acknowledge messages. I'm unsure of any changes you made to the sample to make it work with multiple devices but the sample was originally authored to work with one device and one server to demonstrate the roles. Code published in our docs-samples repos is not intended to be a production grade example for orchestrating large numbers of connected devices. For the latter, you may be better off looking at the [Community Tutorials for IoT Core](https://cloud.google.com/community/tutorials?q=%22Cloud%20IoT%20Core%22) to find more complex examples that serve this purpose.

That said, the e2e example device should be sending messages with QoS 1 (at least once delivery) so until the message is acknowledged in the PubSub queue and the message has not expired (typically 7 days) then the message eventually will appear on subscriptions to the PubSub topic configured with your device registry. If you have changed the sample to instead publish with a QoS of 0, the message could be dropped from the PubSub topic before reaching subscribers.

Also of note, PubSub will not de-duplicate messages for you, so the behavior for messages to be transmitted multiple times to topics and subscriptions is expected.

A final note that is most likely the cause of confusion here is that the sample server does not run indefinitely by default; it runs until a minute has passed. There are no guarantees of [delivery speed that I'm seeing on PubSub](https://cloud.google.com/pubsub/quotas) so your messages may just be getting queued up after the server has shut down. If you change the server code to instead run for a few minutes longer than the devices are transmitting their telemetry, you eventually should see all of the messages arrive at least once. There also can be a warm-up period for inactive or fresh pubsub topics. As you publish more frequently to your topics, the delivery times become more consistent but there can be delays associated with unused or fresh topics.

**Comment by sgreenberg** [comment] 2020-08-24 03:41
This question has been addressed, and there haven't been additional comments. Closing out the issue. Please feel free to reopen if this doesn't seem right.

**Closed by sgreenberg** 2020-08-24 03:41 UTC
Labels: api: cloudiot, priority: p2, samples, type: bug
