### ISSUE TITLE
Unable to add entry with DateTime object

### ISSUE THREAD

**Issue by arnstein** [GoogleCloudPlatform/python-docs-samples#2272] opened 2019-07-17 10:28 UTC
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b32f7df710973170efc5fdfbcf0e5182d13ced7c/firestore/cloud-client/snippets.py#L86-L99
found through the tutorial at [this link](https://cloud.google.com/firestore/docs/manage-data/add-data)
### Did you change the file? If so, how?
No

## Describe the issue
I have made a Python script that adds entries to a collection. When using Datetime.Datetime.now() or a specific date, I get this error in the Cloud logs:
`Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field scheduledStartTime). at Object.validateUserInput (/srv/node_modules/@google-cloud/firestore/build/src/serializer.js:275:15) at validateDocumentData (/srv/node_modules/@google-cloud/firestore/build/src/write-batch.js:614:26) at WriteBatch.create (/srv/node_modules/@google-cloud/firestore/build/src/write-batch.js:143:9) at DocumentReference.create (/srv/node_modules/@google-cloud/firestore/build/src/reference.js:273:14) at MyCollection.create (/srv/lib/classes/Entity.js:46:79) at module.exports.functions.firestore.document.onCreate (/srv/lib/triggers/firestore/collection/onCreate.f.js:38:39) at cloudFunction (/srv/node_modules/firebase-functions/lib/cloud-functions.js:119:23) at /worker/worker.js:825:24 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
`
By translating this script to JavaScript and using new Date() it works perfectly well. Is there an error in the docs? What should you use for timestamps with the Python SDK?

**Comment by BenWhitehead** [comment] 2019-10-09 15:56
I've tried to reproduce the error you're seeing, but haven't been able to with `google-cloud-firestore==1.4.0`. I was able to successfully run and query back the data you have linked to.

Can you provide some details on which version of `google-cloud-firestore` you're using.

**Comment by arnstein** [comment] 2019-10-10 08:37
I don't really use this anymore, but to answer your question:
My version was 1.1.1.

**Comment by BenWhitehead** [comment] 2019-10-10 15:42
@arnstein Thanks for getting back to me.

Since this is no longer blocking you, and I've verified it doesn't affect 1.4.0 I'm going to close this.

**Closed by BenWhitehead** 2019-10-10 15:42 UTC
Labels: needs more info, priority: p2, type: docs
