### ISSUE TITLE
Connection Refused: unacceptable protocol version.

### ISSUE THREAD

**Issue by openedhardware** [GoogleCloudPlatform/python-docs-samples#4924] opened 2020-10-29 02:55 UTC
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py

### Did you change the file? If so, how?

Just replaced the credentials with mine and executed `mqtt_device_demo()` function only.

## Describe the issue
```
Device client_id is 'projects/ConnectedScale/locations/us-central1/registries/connectedscale/devices/scale-1'
Creating JWT using RS256 from private key file utils/private_key.pem
Subscribing to /devices/scale-1/commands/#
Publishing message 1/100: 'connectedscale/scale-1-payload-1'
on_disconnect Connection Refused: unacceptable protocol version.
```

**Comment by openedhardware** [comment] 2020-11-02 21:18
@munkhuushmgl 
Any update here?

**Comment by munkhuushmgl** [comment] 2020-11-02 21:33
ok lemme reproduce it locally.

**Comment by munkhuushmgl** [comment] 2020-11-02 21:39
Looks like it is working as intended. Could you share your command line arguments or Could you check if you are passing right values for parameters?

Service working fine.
![image](https://user-images.githubusercontent.com/45373284/97922081-c6632280-1d10-11eb-8b93-ec7cc9c9aed4.png)

**Comment by openedhardware** [comment] 2020-11-02 21:50
@munkhuushmgl 

```
E:\> python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>quit()

E:\> python cloudiot_mqtt_example.py --algorithm RS256 --device_id scale-1 --private_key_file private_key.pem --regis
try_id connectedscale --ca_certs ca_roots.pem  device_demo
Device client_id is 'projects/None/locations/us-central1/registries/connectedscale/devices/scale-1'
Creating JWT using RS256 from private key file private_key.pem
Subscribing to /devices/scale-1/commands/#
Publishing message 1/100: 'connectedscale/scale-1-payload-1'
on_disconnect 1: Out of memory.
```

`on_disconnect 1: Out of memory.` seems incorrect in `on_disconnect()`.

`print('on_disconnect', error_str(rc))` - this should be replaced with `print('on_disconnect', mqtt.connack_string(rc))`?

So, the new result:
```
E:\> python cloudiot_mqtt_example.py --algorithm RS256 --device_id scale-1 --private_key_file private_key.pem --regis
try_id connectedscale --ca_certs ca_roots.pem  device_demo
Device client_id is 'projects/None/locations/us-central1/registries/connectedscale/devices/scale-1'
Creating JWT using RS256 from private key file private_key.pem
Subscribing to /devices/scale-1/commands/#
Publishing message 1/100: 'connectedscale/scale-1-payload-1'
on_disconnect Connection Refused: unacceptable protocol version.
```

Thanks!

**Comment by openedhardware** [comment] 2020-11-02 21:53
Created a virtualenv to install exact versions in `requirements.txt`, but same result.

**Comment by munkhuushmgl** [comment] 2020-11-02 21:53
> Created a virtualenv to install exact versions in `requirements.txt`, but same result.

What OS is running on?

**Comment by openedhardware** [comment] 2020-11-02 21:54
Tried on Windows/Raspbian/Ubuntu

**Comment by openedhardware** [comment] 2020-11-02 21:59
Is there anything I have to configure on google cloud?

**Comment by munkhuushmgl** [comment] 2020-11-02 23:19
looks like u missing ```--ca_certs ../roots.pem```

**Comment by openedhardware** [comment] 2020-11-02 23:22
Already downloaded by `curl https://pki.goog/roots.pem > roots.pem`. 

Without this, the script doesn't run!  😋

**Comment by munkhuushmgl** [comment] 2020-11-02 23:23
On my end, it is working as intended 
![image](https://user-images.githubusercontent.com/45373284/97930006-60ca6280-1d1f-11eb-9c7d-ff1b624b18bf.png)

**Comment by munkhuushmgl** [comment] 2020-11-02 23:24
I would suggest debugging it, and since it is not service or API related issue, I will be closing this soon.

**Comment by fhinkel** [comment] 2020-12-11 15:43
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Closed by fhinkel** 2020-12-11 15:43 UTC
Labels: api: cloudiot, api: iot, samples, type: question
