### ISSUE TITLE
if args.command.startswith('gateway'): AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by neuberfran** [GoogleCloudPlatform/python-docs-samples#4700] opened 2020-09-17 01:28 UTC
![I can http but I can not mqtt](https://user-images.githubusercontent.com/38701397/93484948-60811f80-f8b7-11ea-8ab9-caef6e4e2ecc.png)
I can with HTTP script BUT I can't with MQTT script. Why????
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iot/api-client/mqtt_example

### Did you change the file? If so, how?
No

## Describe the issue
![issuePythongcp](https://user-images.githubusercontent.com/38701397/93408711-11e96c00-f84a-11ea-8cfc-5ade8eaf942e.png)

key_file=rsa_private.pem
Traceback (most recent call last):
  File "cloudiot_mqtt_example.py", line 513, in <module>
    main()
  File "cloudiot_mqtt_example.py", line 485, in main
    if args.command.startswith('gateway'):
AttributeError: 'NoneType' object has no attribute 'startswith'
![Captura de Tela 2020-09-16 às 18 45 02](https://user-images.githubusercontent.com/38701397/93410355-b0c39780-f84d-11ea-8e8a-3be570ef7783.jpeg)

**Comment by munkhuushmgl** [comment] 2020-09-17 20:36
![image](https://user-images.githubusercontent.com/45373284/93525159-73f9ae00-f8ea-11ea-8576-75da7667f21a.png)
I have looked into current state of IoT's stability and functionality. Everything is working as intended.
you may be using wrong format on keys or somewhere else

**Comment by neuberfran** [comment] 2020-09-18 21:21
It's not works. I try with iptables: https://community.onion.io/topic/2725/mosquitto_pub-error-connection-refused/4 

I try in ubuntu 19.04 native machine, I try in w10 machine and in mac os x 10.15.6 machine. 

But I always had the same issue!

**Comment by neuberfran** [comment] 2020-09-26 04:00
@munkhuushmgl  I can run with this (without gateway) https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py

What about gateway ? Why I need gateway ? How to solve ?

(my issue(

**Comment by gcseh** [comment] 2021-02-03 17:00
This issue has been fixed by #5001

**Closed by gcseh** 2021-02-03 17:00 UTC
Labels: api: cloudiot, samples, type: question
