### ISSUE TITLE
    retry=google.api_core.gapic_v1.method.DEFAULT, AttributeError: 'module' object has no attribute 'api_core'

### ISSUE THREAD

**Issue by sphonala** [GoogleCloudPlatform/python-docs-samples#2520] opened 2019-11-11 10:56 UTC
worked on cloud shell enviornmnt  but got error on instance while list-registries in python-docs-samples/iot/api-client/manager/manager.py 
installed required libraries,
git clone https://github.com/GoogleCloudPlatform/python-docs-samples.git
sudo pip install -r requirements.txt

testdev@instance-1:~/gcloud/python-docs-samples/iot/api-client/manager$ python manager.py --project_id=testdev-a9be0 --cloud_region=us-central1 --service_account_json=./testdev-iotcore.json list-registries

Traceback (most recent call last):
  File "manager.py", line 37, in <module>
    from google.api_core.exceptions import AlreadyExists
  File "/home/testdev/.local/lib/python2.7/site-packages/google/api_core/__init__.py", line 20, in <module>
    from pkg_resources import get_distribution
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    for dist in working_set
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3279, in <genexpr>
    for dist in working_set
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2785, in activate
    declare_namespace(pkg)
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/testdev/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2217, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/testdev/.local/lib/python2.7/site-packages/google/cloud/pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/home/testdev/.local/lib/python2.7/site-packages/google/cloud/pubsub_v1/__init__.py", line 18, in <module>
    from google.cloud.pubsub_v1 import publisher
  File "/home/testdev/.local/lib/python2.7/site-packages/google/cloud/pubsub_v1/publisher/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1.publisher.client import Client
  File "/home/testdev/.local/lib/python2.7/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 29, in <module>
    from google.cloud.pubsub_v1.gapic import publisher_client
  File "/home/testdev/.local/lib/python2.7/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 75, in <module>
    class PublisherClient(object):
  File "/home/testdev/.local/lib/python2.7/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 245, in PublisherClient
    retry=google.api_core.gapic_v1.method.DEFAULT,
AttributeError: 'module' object has no attribute 'api_core'

**Comment by andrewferlitsch** [comment] 2019-12-03 17:53
@gguuss Any update?

**Comment by gguuss** [comment] 2019-12-03 22:12
I didn't even realize this was assigned to me. Anecdotally, tests pass for me and the sample runs without issue. I'll see if I can repro.

**Comment by gguuss** [comment] 2019-12-03 22:15
@sphonala Are you using [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) as explained in [the sample instructions](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iot/api-client/manager)? As I understand it, running `pip install` as root is not advised.

**Comment by gguuss** [comment] 2019-12-03 22:20
Also, try setting the environment variables for your service account JSON and Cloud ID.
```
export GCLOUD_PROJECT=testdev-a9be0
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud/python-docs-samples/iot/api-client/manager/testdev-iotcore.json
```

**Comment by gguuss** [comment] 2019-12-19 20:02
@sphonala Any updates? Can you try running `pip freeze` so we can see what module versions you have installed?

**Comment by sphonala** [comment] 2019-12-21 06:03
Not working on it, but
testdev@instance-1:~$ pip freeze
asn1crypto==1.2.0
astroid==1.6.6
backports.functools-lru-cache==1.6.1
blinker==1.3
boto==2.44.0
CacheControl==0.12.5
cachetools==3.1.1
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
Click==7.0
colorama==0.3.7
configparser==4.0.2
crcmod==1.7
cryptography==2.7
dill==0.2.9
enum34==1.1.6
firebase-admin==2.17.0
flaky==3.6.1
Flask==1.1.1
future==0.16.0
futures==3.3.0
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.17.0
gcp-devrel-py-tools==0.0.15
google-api-core==1.14.3
google-api-python-client==1.7.11
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-cloud-core==1.0.3
google-cloud-firestore==1.3.0
google-cloud-iot==0.3.0
google-cloud-pubsub==1.0.0
google-cloud-storage==1.17.0
google-compute-engine==20190729.0
google-gax==0.16.0
google-resumable-media==0.3.2
googleapis-common-protos==1.6.0
grpc-google-iam-v1==0.12.3
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
grpcio==1.25.0
httplib2==0.14.0
idna==2.8
ipaddress==1.0.23
isort==4.3.21
itsdangerous==1.1.0
Jinja2==2.10.1
jws==0.1.3
keyring==10.1
keyrings.alt==1.3
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
msgpack==0.6.1
oauth2client==4.1.3
packaging==19.2
paho-mqtt==1.4.0
ply==3.8
protobuf==3.10.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.4.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.7.1
pylint==1.9.5
pyOpenSSL==16.2.0
pyparsing==2.4.5
Pyrebase==3.0.27
python-jwt==2.0.1
pytz==2019.3
pyxdg==0.25
requests==2.22.0
requests-toolbelt==0.7.0
retrying==1.3.3
rsa==4.0
SecretStorage==2.3.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.13.0
uritemplate==3.0.0
urllib3==1.25.6
websocket-client==0.56.0
Werkzeug==0.15.5
wrapt==1.11.2

**Comment by sphonala** [comment] 2019-12-21 06:08
> @sphonala Are you using [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) as explained in [the sample instructions](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iot/api-client/manager)?
> 
> ```shell
> virtualenv -p python2 env2
> source env2/bin/activate
> pip install -r requirements.txt
> ...
> ```
> 
> As I understand it, running `pip install` as root is not advised.

No I'm not using

**Comment by gguuss** [comment] 2019-12-26 17:57
Acknowledged, I'll take a look. You may want to try using Virtual Environment to isolate your dependencies. For example, run the following commands before running pip install:

```bash
virtualenv -p python3 env3
source env3/bin/activate
```

**Comment by gguuss** [comment] 2020-01-15 01:02
@sphonala Let me know if virtualenv helps. You can also try running your code from [Cloud Shell](https://cloud.google.com/shell/).

**Comment by gguuss** [comment] 2020-01-17 21:35
It's been a month since this was filed, I'm not able to reproduce the issue and it looks like in this case the environment could have clashing libraries, causing the issue. Please reopen if you retried using virtualenv and still are encountering the issue.

**Closed by gguuss** 2020-01-17 21:35 UTC
Labels: Data Analytics / ML / IoT, api: iot, priority: p2, type: bug
