### ISSUE TITLE
Problems using the client

### ISSUE THREAD

**Issue by radianceltd** [GoogleCloudPlatform/python-docs-samples#2626] opened 2019-12-17 08:21 UTC
I ran into a problem using the client

```
cryptography==2.7
flaky==3.6.1
gcp-devrel-py-tools==0.0.15
google-api-python-client==1.7.11
google-auth-httplib2==0.0.3
google-auth==1.6.3
google-cloud-iot==0.3.0
google-cloud-pubsub==1.0.0
oauth2client==4.1.3
paho-mqtt==1.4.0
pyjwt==1.7.1
```

```
 @classmethod
    def create_gateway(cls, service_account_json, project_id, cloud_region, registry_id, device_id,
            gateway_id, certificate_file, algorithm):
        """Create a gateway to bind devices to."""
        # [START iot_create_gateway]
        # Check that the gateway doesn't already exist

        exists = False

        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = current_app.config['GOOGLE_APPLICATION_CREDENTIALS']

        # credentials = service_account.Credentials.from_service_account_file(
        # "your-json-file - path -with-filename.json")

        client = iot_v1.DeviceManagerClient()

        parent = client.registry_path(project_id, cloud_region, registry_id)
# Error getting device
        devices = list(client.list_devices(parent=parent))

        for device in devices:
            if device.id == gateway_id:
                exists = True
            print('Device: {} : {} : {} : {}'.format(
                device.id,
                device.num_id,
                device.config,
                device.gateway_config
            ))

        with io.open(certificate_file) as f:
            certificate = f.read()

        if algorithm == 'ES256':
            certificate_format = 'ES256_PEM'
        else:
            certificate_format = 'RSA_X509_PEM'

        # TODO: Auth type
        device_template = {
            'id': gateway_id,
            'credentials': [{
                'public_key': {
                    'format': certificate_format,
                    'key': certificate
                }
            }],
            'gateway_config': {
                'gateway_type': 'GATEWAY',
                'gateway_auth_method': 'ASSOCIATION_ONLY'
            }
        }

        if not exists:
            res = client.create_device(parent, device_template)
            print('Created Gateway {}'.format(res))
            return True
        else:
            print('Gateway exists, skipping')
            return False
        # [END iot_create_gateway]

```
```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1576569855.416981000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1576569855.416980000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>
```

**Comment by gguuss** [comment] 2019-12-17 21:51
Thanks for the issue report. Is the code you're sharing never working or it it then working and then stopping to work?  Are you able to do any operations?

**Comment by radianceltd** [comment] 2019-12-18 00:09
Thank you for your reply，my code is not working.

**Comment by radianceltd** [comment] 2019-12-18 00:13
test code is ok. Explain 'GOOGLE_APPLICATION_CREDENTIALSGOOGLE_APPLICATION_CREDENTIALS' is good.
```
 @classmethod
    def implicit(cls):

        # If you don't specify credentials when constructing the client, the
        # client library will look for credentials in the environment.
        storage_client = storage.Client()

        # Make an authenticated API request
        buckets = list(storage_client.list_buckets())
        print(buckets)
```

**Comment by gguuss** [comment] 2019-12-18 00:17
The code that is in the sample repo is working for me. With more information hopefully we'll get it working for you too! It looks like the code you're sharing is a modification of the device management example for adding a Gateway-type device. Note you can also do this using the Google Cloud SDK.

The **GOOGLE_APPLICATION_CREDENTIALS** environment variable is used to grab the path to [service account credentials](https://cloud.google.com/docs/authentication/production) used to authenticate the client to your Google Cloud Platform (GCP) account. You can download them from the [Google Cloud Console](https://console.cloud.google.com).

The storage client is for Google Cloud Storage. What are you trying to do?

**Comment by radianceltd** [comment] 2019-12-18 00:27
This is used to check whether JSON is correct on the document

**Comment by radianceltd** [comment] 2019-12-18 00:28
Why can't I get the list in this code
```
 devices = list(client.list_devices(parent=parent))
```

**Comment by radianceltd** [comment] 2019-12-18 01:46
```
File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x108318e18>, name: "projects/tmw025/locations/us-central1/registries/my-registry/devices/device-002"
, metadata=[('x-goog-request-params', 'name=projects/tmw025/locations/us-central1/registries/my-registry/devices/device-002'), ('x-goog-api-client', 'gl-python/3.7.0 grpc/1.25.0 gax/1.15.0 gapic/0.3.0')]), last exception: 503 failed to connect to all addresses
```

**Comment by radianceltd** [comment] 2019-12-18 01:51
```

[2019-12-18 09:45:57,643] ERROR in app: Exception on /test/add_gateway/ [POST]
Traceback (most recent call last):
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/grpc/_channel.py", line 690, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/grpc/_channel.py", line 592, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1576633517.745266000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1576633481.048746000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rnd/Desktop/AllProject/Python/iotcore_test/app/web/googlecore.py", line 24, in device
    isok = GoogleCore.create_gateway('', project_id, 'us-central1', registry_id, device_id, gateway_id, '', algorithm)
  File "/Users/rnd/Desktop/AllProject/Python/iotcore_test/app/spider/google_core.py", line 68, in create_gateway
    isok = client.delete_device(device_path)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/cloud/iot_v1/gapic/device_manager_client.py", line 950, in delete_device
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/Users/rnd/.local/share/virtualenvs/iotcore_test-cNntKDwd/lib/python3.7/site-packages/google/api_core/retry.py", line 206, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x108318e18>, name: "projects/tmw025/locations/us-central1/registries/my-registry/devices/device-002"
, metadata=[('x-goog-request-params', 'name=projects/tmw025/locations/us-central1/registries/my-registry/devices/device-002'), ('x-goog-api-client', 'gl-python/3.7.0 grpc/1.25.0 gax/1.15.0 gapic/0.3.0')]), last exception: 503 failed to connect to all addresses
192.168.0.55 - - [18/Dec/2019 09:45:57] "POST /test/add_gateway/ HTTP/1.1" 500 -
```

**Comment by gguuss** [comment] 2019-12-18 02:11
A few questions that will help me understand:

* Does the `my-registry` registry exist in the `us-central1` region for the tmw025 project?
* Do other commands work, e.g. does list registries work?
* What is the output of `pip freeze`? I'm curious about your GRPC dependencies.

**Comment by gguuss** [comment] 2019-12-18 02:14
My guess is that you need to download a service account credentials json file and pass its correct path when you are calling **create_gateway**.

**Comment by radianceltd** [comment] 2019-12-18 02:28
I have configured the downloaded JSON file. 

Is my configuration correct

```
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = current_app.config['GOOGLE_APPLICATION_CREDENTIALS']
        print(os.environ['GOOGLE_APPLICATION_CREDENTIALS'])
```

**Comment by radianceltd** [comment] 2019-12-18 02:29
```
GOOGLE_APPLICATION_CREDENTIALS = '/Users/rnd/Desktop/AllProject/Python/iotcore_test/app/web/TMW025_google.json'
```

**Comment by radianceltd** [comment] 2019-12-18 02:34
1. Us-central1 region in registry
2. No other command

**Comment by radianceltd** [comment] 2019-12-18 02:35
I used the source code to build part of the code for testing，I'm use flask

**Comment by radianceltd** [comment] 2019-12-18 02:43
My-registry is in us-central1 region.
Others can't run either.

**Comment by radianceltd** [comment] 2019-12-19 09:06
@gguuss Whether login authorization verification is required？

**Comment by gguuss** [comment] 2019-12-19 18:05
It looks like this is a duplicate of [this issue](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2638), closing.

**Closed by gguuss** 2019-12-19 18:05 UTC
Labels: api: iot, triage me
