### ISSUE TITLE
Django App Deploy on Cloud Run

### ISSUE THREAD

**Issue by LekiaAnonim** [GoogleCloudPlatform/python-docs-samples#7615] opened 2022-03-19 21:35 UTC
Hello, I am trying to deploy a Django app using Cloud Run. I am following the guide in https://cloud.google.com/python/django/run#console_3
I successfully submit my container using the command: 
gcloud builds submit --config cloudmigrate.yaml --substitutions _INSTANCE_NAME=postgres,_REGION=us-central1 

but the cloud deploy is returning the error "Internal error occurred while performing container health check."
My deploy command is  
gcloud run deploy koretgist-brew --platform managed --region us-central1 --image gcr.io/koretgist/koretgist-brew --add-cloudsql-instances koretgist:us-central1:postgres --allow-unauthenticated

When I tried running makemigrations command locally, I am getting the following error messages:

Traceback (most recent call last):
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\manage.py", line 22, in <module>
    main()
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\venv\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\venv\lib\site-packages\django\core\management\__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\venv\lib\site-packages\django\conf\__init__.py", line 87, in 
__getattr__
    self._setup(name)
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\venv\lib\site-packages\django\conf\__init__.py", line 74, in 
_setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\venv\lib\site-packages\django\conf\__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\TOSHIBA\Desktop\PilotXLab\Django\koretgist-brew\koretgist-brew\koretgist\settings.py", line 40, in <module>
    _, os.environ["GOOGLE_CLOUD_PROJECT"] = google.auth.default()
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python39\lib\os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python39\lib\os.py", line 742, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

**Comment by LekiaAnonim** [comment] 2022-03-20 19:59
Any help, please?

My settings.py and Dockerfile is the same as what we have in 
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/run/django

**Comment by parthea** [comment] 2022-03-21 17:54
Hi @LekiaAnonim,

I was able to re-produce the stack trace by using a value of `None`. The issue is that `google.auth.default()` is not able to find default credentials automatically and as a result `google.auth.default()` is returning `None`. In order to use `google.auth.default()`, please configure the credentials using the steps here: https://googleapis.dev/python/google-auth/latest/reference/google.auth.html#google.auth.default. I'm going to close this issue as I believe this is just a matter of credentials not being set in your environment but please feel free to re-open it with more information.


```
>>> import os
>>> os.environ["some-key"]=None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```

**Closed by parthea** 2022-03-21 17:54 UTC
Labels: triage me, samples

**Comment by LekiaAnonim** [comment] 2022-03-21 22:15
Thank you for your response. The issue has been resolved.

Lekia Prosper Kiisi
MSc. Petroleum Engineering
African University of Science and Technology
Abuja, Nigeria
Email: ***@***.*** | ***@***.***
Mobile/WhatsApp: +2348137110189 | +2349134140259
LinkedIn <https://www.linkedin.com/in/prosper-kiisi-88495b1a9/>
Medium <https://lekiaprosper.medium.com/>          GitHub
<https://github.com/LekiaAnonim>
