### ISSUE TITLE
Confusion about use of FIREBASE_PROJECT_ID in firenotes sample

### ISSUE THREAD

**Issue by embray** [GoogleCloudPlatform/python-docs-samples#4268] opened 2020-07-09 11:19 UTC
## In which file did you encounter the issue?

[appengine/standard/firebase/firenotes/backend/app.yaml](../blob/master/appengine/standard/firebase/firenotes/backend/app.yaml)

## Describe the issue

In [this tutorial](https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine) a `FIREBASE_PROJECT_ID` environment variable is specified in the `app.yaml`, but it doesn't appear to be used anywhere.  I imagine it should be passed as the `audience` argument to [`verify_firebase_token`](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.id_token.html#google.oauth2.id_token.verify_firebase_token).  Since this wasn't done in the example code I thought that environment variable might be recognized by the library as providing a default for this argument, but as far as I can tell that isn't the case.

It would be nice to clarify this example.

**Comment by tmatsuo** [comment] 2020-07-16 22:46
@averikitsch Can you take a look?

**Comment by engelke** [comment] 2020-07-16 23:09
You're right that this environment variable was used to check the audience of the token. However, at some point the authentication library was updated to automatically make that check, and the code no longer used this variable at all, not even implicitly. Removed in PR https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4311

**Comment by embray** [comment] 2020-07-17 12:33
@engelke Could you clarify what you mean by

> at some point the authentication library was updated to automatically make that check

?

The API docs state that if `audience` (typically the project ID) is not passed, then it will not be verified.  So where does the value for this come from then if the check is done automatically?

**Comment by engelke** [comment] 2020-07-20 22:08
You're right. I was thinking about the issuer field, not the audience. It should be checked, and must be passed. So the problem is not that an unneeded environment variable is included, it is that a needed one is never used. Fixed in PR #4336

**Closed** 2020-07-21 17:46 UTC
Labels: :rotating_light:, api: appengine, triage me
