### ISSUE TITLE
Firestore test, test_listen_document, freezes and crashes CI

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2442] opened 2019-10-05 00:09 UTC
Running [the code on our automation is failing](https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/builds/593780642), maybe the test is forking a process that never terminates?

This issue is to track and resolve this stuck test.

**Comment by gguuss** [comment] 2019-10-05 01:09
It actually looks like the `test_listen_*` tests may be failing?

**Comment by BenWhitehead** [comment] 2019-10-06 18:58
This is caused by googleapis/google-cloud-python#9008 which has a merged fix in googleapis/google-cloud-python#9337. We're just waiting on a new release of google-cloud-core with the fix.

**Comment by BenWhitehead** [comment] 2019-10-06 18:59
Related PR blocked by this same issue: #2427

**Comment by BenWhitehead** [comment] 2019-10-09 15:51
My PR #2427 is now passing CI. @gguuss I've triggered a new build for the link you provided. If it's green, I'll close this issue.

**Comment by BenWhitehead** [comment] 2019-10-09 19:39
When I tried to re-run the build it failed because the PR had already been merged.

@gguuss Is it okay to close this now that the listen tests are working again?

**Comment by gguuss** [comment] 2019-10-09 19:50
Yes, go ahead and close, I have verified this is passing now.

**Closed** 2019-10-09 20:37 UTC
Labels: priority: p1, type: bug
