### ISSUE TITLE
Cannot load newline JSON data in GCS with a nested schema. Field: product

### ISSUE THREAD

**Issue by jaehancrate** [GoogleCloudPlatform/python-docs-samples#1262] opened 2017-12-08 17:40 UTC
Hello, 

I am trying to load a file from GCS bucket.. I have tried uploading from a local file and from google storage and I get this error both times:

![image](https://user-images.githubusercontent.com/20776752/33777928-4cd7263e-dc0c-11e7-928a-a5982d049c30.png)

Here is a code snippet:

![image](https://user-images.githubusercontent.com/20776752/33778018-8dd836e6-dc0c-11e7-9640-a6a7a1c2ec75.png)

**Comment by jonparrott** [comment] 2017-12-08 18:16
@tswast @alixhami can one of you take a look?

**Comment by tswast** [comment] 2017-12-08 18:17
@jaehancrate Could you provide a sample of a minimal CSV file that reproduces the issue?

**Comment by jaehancrate** [comment] 2017-12-08 18:28
Sorry I wrote the wrong title... It's a newline delimited json file in GCS. 

Here is an example of sample data
[data_sample.txt](https://github.com/GoogleCloudPlatform/python-docs-samples/files/1543499/data_sample.txt)

**Comment by tswast** [comment] 2017-12-08 18:45
Ah, okay. In that case, note that `CSV` is the default file type. To change the load job to use newline delimited JSON, use the `LoadJobConfig` class. I'll make a note to add a JSON sample to the docs.

This should get you started.

    table_ref = dataset_ref.table(table_id)
    job_config = bigquery.LoadJobConfig()
    job_config.source_format = 'NEWLINE_DELIMITED_JSON'
    job = client.load_table_from_uri(source, table_ref, job_config=job_config)  # API request
    job.result()  # Waits for table load to complete.

**Comment by jaehancrate** [comment] 2017-12-11 15:04
![image](https://user-images.githubusercontent.com/20776752/33837504-274c63f0-de52-11e7-88d1-dd72381515dd.png)

![image](https://user-images.githubusercontent.com/20776752/33837530-3e151406-de52-11e7-8f1c-520db0a5ff51.png)

That is the exact code I just ran... it still recognizes those files as a CSV

**Comment by tswast** [comment] 2017-12-11 16:14
Looks like you forgot to pass the LoadJobConfig to the `load_table_from_uri` function.

In your code, change to:

```
job = client.load_table_from_uri('gs://product_temp_bucket/ProductTemp', table_ref, job_config=job) 
```

**Comment by jaehancrate** [comment] 2017-12-11 16:19
Yikes, that was a dumb mistake. 
I'm getting a 400 error however... 
![image](https://user-images.githubusercontent.com/20776752/33841191-a75d29c6-de5c-11e7-945f-d05e5210a6f3.png)

I'm not sure what the issue is here. When I inspect the GCS bucket it looks fine. I am positive it is in the right format..

**Comment by jaehancrate** [comment] 2017-12-11 16:19
[data_sample.txt](https://github.com/GoogleCloudPlatform/python-docs-samples/files/1548471/data_sample.txt)

Here is a data sample

**Comment by jaehancrate** [comment] 2017-12-11 16:25
![image](https://user-images.githubusercontent.com/20776752/33841491-7d349160-de5d-11e7-826d-85ddb67d9e76.png)


I am currently running it from a file upload and it hasn't erred yet, will comment once finished. 
Curious though why the from_uri method doesn't work for me.

**Comment by tswast** [comment] 2017-12-11 16:30
Interesting. Thanks for the update. I'll try with your example file in a bit.

**Comment by jaehancrate** [comment] 2017-12-11 16:38
Still having issues... I even tried to do so with a .json version of the same file content. 
![image](https://user-images.githubusercontent.com/20776752/33842162-5f371c12-de5f-11e7-8434-d328f1356d53.png)

**Comment by tswast** [comment] 2017-12-11 17:16
Does the table already exist? If so, do you want to overwrite to it or append to it?

**Comment by jaehancrate** [comment] 2017-12-11 17:17
Yes the table exists and I want to overwrite it

**Comment by jaehancrate** [comment] 2017-12-11 17:18
I want to overwrite it, and yes it does

*Jae Han*
Marketing Automation Developer,
Marketing Automation and Technology Management


1250 Techny Road
Northbrook, IL 60062
W (847) 239-6659
M (317) 219-9758

This email and any attachments may contain information that is privileged,
confidential and/or subject to attorney/client privilege, attorney work
product, intellectual property or other protections. If you have received
this email in error, please delete the message and any attachments and
notify the sender immediately. Please do not disseminate, copy or
distribute this information.

**Comment by tswast** [comment] 2017-12-11 17:48
In that case, probably also want to set [`job_config.write_disposition = 'WRITE_TRUNCATE'`](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html#google.cloud.bigquery.job.LoadJobConfig.write_disposition).

**Comment by tswast** [comment] 2017-12-11 17:54
I am able to load your sample file using the following code (to a new table).

```
from google.cloud import bigquery

client = bigquery.Client()

dataset_ref = client.dataset('test_dataset')
table_ref = dataset_ref.table('Product')

job_config = bigquery.LoadJobConfig()
job_config.source_format = 'NEWLINE_DELIMITED_JSON'
job_config.autodetect = True

with open('data_sample.txt', 'rb') as source_file:
    job = client.load_table_from_file(source_file, table_ref, job_config=job_config)

job.result()
```

Since you are going to an existing table, my only guess is that the schema does not align with the file that you are uploading.

**Comment by jaehancrate** [comment] 2017-12-11 21:56
Which version are you using? I can't find where I am off with my schema it looks right. 

For some reason I am getting an error when I try to do job_config.autodetect = True

**Comment by jaehancrate** [comment] 2017-12-11 21:58
Is there a way to autodetect schema using load job config?

**Comment by engelke** [comment] 2018-12-05 17:14
Issue is addressed in above comments.

**Closed by engelke** 2018-12-05 17:14 UTC
Labels: Fixit
