### ISSUE TITLE
Datastore tests fail if there's invalid entities in the DB

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/python-docs-samples#2469] opened 2019-10-10 21:13 UTC
Repro:
* Create an entity in the visits table with empty IP address
* Run the tests
* Fail!

Fix:
* Remove entities with empty IP addresses
* Run the tests
* Success!

I am not sure who the right person to update this is but we should either clean up the visit entities before running the test or make the tests resilient to empty IPs.

**Comment by leahecole** [comment] 2019-11-15 23:40
@grant I'm assigning this to you because you have touched datastore in the past 6 months, but feel free to triage to someone more relevant!

**Comment by grant** [comment] 2019-11-16 14:29
Hi @leahecole, I don't believe I'm the right person to reassign this bug to. I have touched many files, including this one for a fixit bug. I would reassign this GitHub issue to someone who is a CODEOWNER or works on Datastore.

Perhaps assign to someone who contributed most of the sample code?
https://github.com/GoogleCloudPlatform/python-docs-samples/commits/master/datastore

**Comment by leahecole** [comment] 2019-11-18 16:46
Np Grant. It seems like Thea wrote a lot of the original stuff and we don't have a CODEOWNERS for this repo, but I'm going try @crwilcox for assignment or for him to triage/reassign, given that he's on SoDA :)

**Comment by andrewferlitsch** [comment] 2019-12-03 17:56
@BenWhitehead If this is a Fusion related, should this be as a bug in buganizer and not an issue here?

**Comment by BenWhitehead** [comment] 2019-12-03 19:51
Based on my reading of the issue it sounds like the test setup/teardown isn't properly bounded and the test suite can be broken by leftover/miscreated data. Which leads me to believe the code change will need to happen in the tests in this repo.

**Comment by gguuss** [comment] 2019-12-03 22:10
+1 to what @BenWhitehead said, this is an issue on setup/teardown. If possible we should create a new Datastore at the start of tests then Delete it after the tests run. Or, [clean up the datastore](https://cloud.google.com/datastore/docs/bulk-delete) after the tests run.

**Comment by BenWhitehead** [comment] 2019-12-03 22:21
We'll have to do some form of cleanup, since there isn't currently an api to get a new Datastore instance (and there can only be one Datastore db per project).

**Comment by andrewferlitsch** [comment] 2020-03-17 22:51
@BenWhitehead PTAL

**Comment by BenWhitehead** [comment] 2020-03-19 18:50
Reclassifying as `cleanup` as this is only affecting the tests and not a bug for our customers or the samples themselves.

**Comment by tmatsuo** [comment] 2020-05-15 18:10
Which test is this?

I don't understand why this is left unsolved for a long time. Is it very difficult to fix? I would estimate 1 hour at the best to 1 day of work at the worst.

**Comment by tmatsuo** [comment] 2020-05-15 19:23
I think it is the one:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/23cf90350128b3d2dd7c6add1ff95bbfbc27e307/appengine/flexible/datastore/main.py

**Comment by tmatsuo** [comment] 2020-05-15 19:34
Failure reproduced with running the following code before the test:

```python
import datetime

from google.cloud import datastore


ds = datastore.Client()

for i in range(10):
    entity = datastore.Entity(key=ds.key('visit'))

    entity.update({
        'timestamp': datetime.datetime.utcnow() + datetime.timedelta(hours=10)
    })

    ds.put(entity)
```

**Comment by tmatsuo** [comment] 2020-05-15 19:35
Deleting entities will cause some issues with multiple builds. Maybe we can just relax the test.

**Closed** 2020-05-15 19:55 UTC
Labels: Fixit, api: datastore, type: cleanup
