### ISSUE TITLE
IoT Core MQTT example Does not Connect on 443 from Compute Engine VMs

### ISSUE THREAD

**Issue by jakeczyz** [GoogleCloudPlatform/python-docs-samples#2152] opened 2019-05-14 16:02 UTC
## In which file did you encounter the issue?
python-docs-samples/iot/api-client/mqtt_example/cloudiot_mqtt_example.py

### Did you change the file? If so, how? 
Nope.

## Describe the issue
Python Paho MQTT client is no longer able to connect to  IoT core registries over port 443, whereas 8883 still works.  This appears to only be a problem from Compute Engine VMs. It works fine from external machines including my laptop and Digital Ocean VMs.  I've tried multiple registries,, multiple devices, multiple VMs in multiple GCP projects and regions (mostly us-central-1, however).  Both the endpoints: mqtt.googleapis.com and mqtt.2030.ltsapis.goog are exhibiting this behavior.  It worked fine until around mid last week.   I did try the recommended troubleshooting step of connecting via openssl s_client to the endpoints on port 443, and that seems to work fine (see below); so it's not likely a simple network ACL. The VMs are vanilla ubuntu 18.04 LTS-minimal.  

For example, here's how the problem manifests when using the Google MQTT client example code (unmodified), directly from:  github.com:GoogleCloudPlatform/python-docs-samples.git/python-docs-samples/iot/api-client/mqtt_example/cloudiot_mqtt_example.py:

Using port 8883, it looks like this (works fine): 

$ python3 -u ./cloudiot_mqtt_example.py --device_id=MY_AGENT --registry_id=MY_REG --project_id=MY_PROJ --cloud_region=us-central1 --algorithm=ES256 --private_key_file=key.pem --ca_certs=roots.pem --mqtt_bridge_port 8883

Device client_id is 'projects/MY_PROJ/locations/us-central1/registries/MY_REG/devices/MY_AGENT'
Creating JWT using ES256 from private key file key.pem
Subscribing to /devices/MY_AGENT/commands/#
Publishing message 1/100: 'MY_REG/MY_AGENT-payload-1'
on_connect Connection Accepted.
Publishing message 2/100: 'MY_REG/MY_AGENT-payload-2'
... Etc.

Using port 443 (using identical VM, device, registry, project, code, key, certs, time of day, etc.): 

$ python3 -u ./cloudiot_mqtt_example.py --device_id=MY_AGENT --registry_id=MY_REG --project_id=MY_PROJ --cloud_region=us-central1 --algorithm=ES256 --private_key_file=key.pem --ca_certs=roots.pem --mqtt_bridge_port 443

Device client_id is 'projects/MY_PROJ/locations/us-central1/registries/MY_REG/devices/MY_AGENT'
Creating JWT using ES256 from private key file key.pem
Subscribing to /devices/MY_AGENT/commands/#
Publishing message 1/100: 'MY_REG/MY_AGENT-payload-1'
on_disconnect 1: Out of memory.
Waiting for 1.117 before reconnecting.
Publishing message 2/100: 'MY_REG/MY_AGENT-payload-2'
on_disconnect 1: Out of memory.
Waiting for 2.613 before reconnecting.
... Etc.
(NOTE that on_connect is never called)

No TCP/443 outbound block to the google endpoint either: 
$ echo ""| openssl s_client -connect mqtt.googleapis.com:443  | grep CONNECT
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = mqtt.googleapis.com
verify return:1
CONNECTED(00000003)
DONE

Again, this works fine from several machines *outside of compute engine* on same OS (vanilla Ubuntu 18.04 LTS).   The behavior is the same at least for python 3.6.4 and 2.7.14.

**Comment by gguuss** [comment] 2019-05-15 21:29
@jakeczyz Thank you for the report!

This is super weird because I have seen the opposite to be true (8883 not working, 443 working). I'll see if reporting this internally helps.

**Comment by gguuss** [comment] 2019-05-15 21:39
/FYI I was able to reproduce the issue.

**Comment by jakeczyz** [comment] 2019-05-16 01:10
Thanks Gus. Let me know if any other detail is useful!

**Comment by gguuss** [comment] 2019-05-17 17:16
@jakeczyz This has now been fixed, closing the issue. Please reopen if you're still able to reproduce.

**Closed by gguuss** 2019-05-17 17:16 UTC

**Comment by jakeczyz** [comment] 2019-05-18 01:49
I can confirm that my code on Compute Engine can now connect over 443 again. Many thanks for the quick help.

Is there anything you can publicly share about the root cause, or is it all googly secret sauce? :)
