### ISSUE TITLE
GAE websockets support flask-socketio

### ISSUE THREAD

**Issue by Altiire** [GoogleCloudPlatform/python-docs-samples#2196] opened 2019-06-06 12:44 UTC
## In which file did you encounter the issue?

app.yaml

### Did you change the file? If so, how?

Nope

## Describe the issue

My project is using Flask-Socketio for websocket support.
My entrypoint is: `entrypoint: gunicorn supervisor.wsgi:app -k eventlet`
I also set `network: session_affinity: true`

Everything is running except the websocket, I get the following error on Firefox:
`Firefox can’t establish a connection to the server at wss://myproject.appspot.com/socket.io/?EIO=3&transport=websocket&sid=500afafea543442dad546cc325ce5def.`

There is no such error when running my project with the same command on my computer.

**Comment by andrewsg** [comment] 2019-09-03 16:36
The samples are built around flask-sockets so that we can leverage the gunicorn flask_sockets.worker, which allows gunicorn to simultaneously serve http and websocket traffic. I don't think socketio on Python is compatible with gunicorn out of the box; you may have to explore alternative webservers to make this work.

I don't know why it's working on your local machine, though. What command are you running locally to start the server?

**Comment by Altiire** [comment] 2019-09-04 08:22
To support web sockets :
```
python supervisor/app.py
```
sample of **supervisor/app.py**
```python
def create_app(testing=False, cli=False):
    """Application factory, used to create application
    """
    app = Flask('supervisor')
    CORS(app)
    app.config.from_object('supervisor.config')

    if testing is True:
        app.config['TESTING'] = True

    force_auto_coercion()
    configure_extensions(app, cli)
    register_blueprints(app)

    socketio.init_app(app)

    return app

if __name__ == '__main__':
    app = create_app()
    socketio.run(app)
```

If I remember well, the socket was working on GAE in July, and not now as I just checked

> I don't think socketio on Python is compatible with gunicorn out of the box; you may have to explore alternative webservers to make this work.

The eventlet worker is supposed to support socketio

**Comment by andrewsg** [comment] 2020-03-09 17:48
Closing this as we don't currently have a good solution for adding support for both socketio and other strategies in the same sample on Python, and it's not a bug in an existing sample.

**Closed by andrewsg** 2020-03-09 17:48 UTC
Labels: :rotating_light:, api: appengine, priority: p2, type: bug
