### ISSUE TITLE
flaky tests: IAM Service account test failing Python3.9

### ISSUE THREAD

**Issue by holtskinner** [GoogleCloudPlatform/python-docs-samples#10243] opened 2023-06-14 18:01 UTC
- Discovered in #10231 IAM Service account test is failing Python3.9
- `service_accounts_test.test_service_accounts`
- https://source.cloud.google.com/results/invocations/b72823db-d316-485f-ba4d-5c028fa72b1b/targets/github%2Fpython-docs-samples%2Fiam%2Fapi-client/tests

```
Traceback (most recent call last):
  File "/workspace/iam/api-client/service_accounts_test.py", line 36, in test_service_accounts
    service_accounts.rename_service_account(unique_id, "Updated Py Test Account")
  File "/workspace/iam/api-client/service_accounts.py", line 114, in rename_service_account
    service.projects().serviceAccounts().get(name=resource).execute()
  File "/workspace/iam/api-client/.nox/py-3-9/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/workspace/iam/api-client/.nox/py-3-9/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://iam.googleapis.com/v1/projects/-/serviceAccounts/105186979449173761854?alt=json returned "Service account projects/-/serviceAccounts/105186979449173761854 does not exist.". Details: "Service account projects/-/serviceAccounts/105186979449173761854 does not exist.">
```

**Comment by leahecole** [comment] 2023-06-15 14:21
Duplicate of #9965

**Closed by leahecole** 2023-06-15 14:21 UTC
Labels: triage me, priority: p2, type: bug, api: iam, samples
