### ISSUE TITLE
How to send structured log in jsonPayload instead of textPayload in python cloud function. 

### ISSUE THREAD

**Issue by clarencedesmarais** [GoogleCloudPlatform/python-docs-samples#5036] opened 2020-12-04 04:48 UTC
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/run/logging-manual/main.py

### Did you change the file? If so, how?

Very little. Here is what i am using : 

```python
import json
from flask import current_app, escape

def hello(request):
    # Build structured log messages as an object.
    global_log_fields = {}

    # Add log correlation to nest all log messages.
    trace_header = request.headers.get('X-Cloud-Trace-Context')

    if trace_header :
        trace = trace_header.split('/')
        global_log_fields['logging.googleapis.com/trace'] = (
            f"projects/my-project/traces/{trace[0]}")

    # Complete a structured log entry.
    entry = dict(severity='INFO',
                message='This is a test f.',
                otherProp=2,
                # Log viewer accesses 'component' as jsonPayload.component'.
                component='arbitrary-property',
                **global_log_fields)
    
    print(json.dumps(entry))

    subject = request.args.get('subject', 'World')
    subject = escape(subject)
    
    return f'Hello, {subject}!'
```

I'm not providing any environment variables. 

## Describe the issue

When running locally, the log shows up as : 
```sh
{"severity": "INFO", "message": "This is a test f.", "otherProp": 2, "component": "arbitrary-property"}
```
However in GCP, the log should show up in `jsonPayload` but instead shows up in `textPayload`

![image](https://user-images.githubusercontent.com/71276060/101123066-f167bd00-35c1-11eb-828f-6bcdb9a3416e.png)

What do I need to do to make sure the object is logged within the jsonPayload and not the textPayload ? 

I've googled around a bit and it seems this problem was reported here as well. https://stackoverflow.com/questions/64935095/writing-structured-json-log-messages-from-python-google-cloud-function

**Comment by Daniel-Sanche** [comment] 2020-12-11 18:39
Are you using Python 3.7? My understanding is that Python 3.7 doesn't support structured logging, but Python 3.8 should

But I'm mostly familiar with the logging client libraries, which is not used in the Cloud Functions environment. Ace, do you have any more information here?

**Comment by ace-n** [comment] 2020-12-11 22:08
Not off the top of my head; I believe this is a known problem.

cc @vinod-at-google

**Comment by canichet** [comment] 2021-01-22 16:49
Upgrading cloud function to run on Python 3.8 did the trick!

**Comment by go-bears** [comment] 2021-03-18 19:37
I'm seeing the same problem when implementing some new logging. However, our older logging struc() is still being processed by python 3.7 in our Dev and Prod environments as jsonPayLoad correctly in google operations. 

The docś mention something about legacy GKE but how can one know if they're running in a legacy environment?  


<img width="899" alt="Screen Shot 2021-03-18 at 12 27 54 PM" src="https://user-images.githubusercontent.com/6887377/111685763-8a26ef00-87e5-11eb-8ca6-18f5ee02c616.png">

**Comment by Daniel-Sanche** [comment] 2021-03-18 19:50
@go-bears Can you describe your environment a bit more? This issue was related to Cloud Functions, but it sounds like you're using GKE? Are you using the [GCP logging client library](https://github.com/googleapis/python-logging), or printing to standard output?

Can you provide a code snippet, what you're seeing, and what you expected to see?

**Comment by go-bears** [comment] 2021-03-18 20:57
We're using google-cloud-logging==1.14.0
and have a python wrapper around the google cloud logging utility.

```python
from google.cloud import logging

class GCLogger(KLog):
    def __init__(self, project, name):
        client = logging.Client(project=project)
        self.logger = client.logger(name=name)
        self._trace_id = b3_trace_id()

    def _get_data(self) -> dict:
        func = inspect.currentframe().f_back.f_back.f_back.f_back.f_back.f_code
        data = {
            "tracking": {
                "b3-traceId": self._trace_id
            },
            "func": {
                "name": func.co_name,
                "file": func.co_filename,
                "line": func.co_firstlineno
            }
        }
        return data

    def log(self, message: str, category: str, level: str):
        data = self._get_data()
        data.update({"message": message})
        self.log_struct(data, category=category, level=level)

    def log_struct(self, values: Dict, category: str, level: str):
        data = self._get_data()
        data.update(values)
        data.update({"category": category})
        data.update({"severity": level})
        self.logger.log_struct(data)
 ```
We're seeing the payload being processed as json
 
<img width="1019" alt="Screen Shot 2021-03-18 at 12 52 04 PM" src="https://user-images.githubusercontent.com/6887377/111693895-6c11bc80-87ee-11eb-8651-5be24f499f95.png">

Whereas the same  struc() logging code is pulling the values as json in another log:
<img width="558" alt="Screen Shot 2021-03-18 at 1 48 15 PM" src="https://user-images.githubusercontent.com/6887377/111696077-15f24880-87f1-11eb-87b7-a6ce9563a20e.png">

We can't build the dashboard around "reward" metrics parsed from the textPayLoad, yes? Only from the jsonPayLoad.

We're starting to think may be caused by the switch to `Operations for GKE` and deprecation of logging and monitoring of GKE versions 1.17 & below (our cluster is v 1.16?

**Comment by daniel-sanche** [comment] 2021-05-19 17:55
@go-bears Sorry, I must have missed your last comment. If you're still seeing the issue, feel free to open a bug in the [python-logging library repo](https://github.com/googleapis/python-logging/issues) (along with reproducing code if possible) and I can assist there.

I'm going to close this one, since the original problem was addressed

**Closed by daniel-sanche** 2021-05-19 17:55 UTC
Labels: api: logging, priority: p2, samples, type: bug
