### ISSUE TITLE
Better deployment logs and error messages for AI Platform custom prediction routine with PyTorch

### ISSUE THREAD

**Issue by ToddMorrill** [GoogleCloudPlatform/python-docs-samples#4046] opened 2020-06-10 13:32 UTC
I'm following [this guide](https://cloud.google.com/ai-platform/prediction/docs/custom-prediction-routines#model-directory) to deploy a PyTorch model to the AI Platform Prediction service.

## Describe the issue
I get the following error no matter what I do.
```
ERROR: (gcloud.beta.ai-platform.versions.create) Create Version failed. Bad model detected with error: Model requires more memory than allowed. Please try to decrease the model size and re-deploy. If you continue to experience errors, please contact support.
```

So here's the sequence of events that a developer goes through.
1) [See this post](https://cloud.google.com/blog/products/ai-machine-learning/ai-in-depth-serving-a-pytorch-text-classifier-on-ai-platform-serving-using-custom-online-prediction). Awesome! We can deploy PyTorch models to the AI Platform.
2) But wait, there's a gotcha - you can't _actually_ install torch as describe in the post above. You have to do it [this way](https://stackoverflow.com/questions/60423140/pytorch-model-deployment-in-ai-platform).
3) Hmm, I'm still getting this memory issue but my model directory on Google Cloud Storage is only 80mb, and my model only requires 300mb of memory locally. I continue Googling around for a while and then stumble on [this post](https://issuetracker.google.com/issues/142580717) that suggests creating wheels for any package that might require a lot of memory during pip installation. I created wheels for all my packages taking into account what already exists in the [runtime version](https://cloud.google.com/ai-platform/prediction/docs/runtime-version-list), uploaded them to Google Cloud Storage and passed in those paths to the `--package-uris` argument. Same error as above.
    - NB: [this post](https://issuetracker.google.com/issues/142580717) + [the docs](https://cloud.google.com/ai-platform/prediction/docs/custom-prediction-routines) are somewhat confusing regarding this 500mb constraint. It's unclear what the _memory_ and _storage_ constraints are. Does the 500mb model directory (i.e. `--origin`) _storage_ limit include the `--package-uris` or does `--package-uris` not count toward that limit? Is the _memory_ of the deployment environment (suppose `--machine-type mls1-c1-m2`) [2gb](https://cloud.google.com/ai-platform/prediction/docs/machine-types-online-prediction) or [500mb](https://issuetracker.google.com/issues/142580717)?

I even ran another test to see if I could get a different error message. First I tried to deploy my PyTorch model as one would expect. I got the error message above.

I _deleted_ the model weights that were stored in Google Cloud Storage (the ones that would have been loaded by the predictor class) and I still got the error message.

**Comment by busunkim96** [comment] 2020-06-11 22:54
@dizcology Could you triage this please?

**Comment by ToddMorrill** [comment] 2020-06-27 20:44
FWIW, I think the issue stemmed from unsatisfied Python packages dependencies (and surely I could have done more local testing) but I still think better logs should be surfaced to the user so that they can debug deployments to the cloud.

**Comment by busunkim96** [comment] 2020-06-29 20:30
Friendly ping @dizcology or @ericschmidtatwork could you take a look?

**Comment by rhaertel80** [comment] 2021-01-06 21:20
The problem is that the approach outlined above brings in a lot of dependencies and those get counted against the RAM usage as the downloads are stored in TMPFS. The most recent guidelines for running PyTorch can be found in the public docs and you should not hit the same issue:

https://cloud.google.com/ai-platform/prediction/docs/getting-started-pytorch-container

To answer your question, we enforce a 500 MB limit for mls1* machines and 2 Gb limit for n1* machines for files on GCS, but each machine also has a RAM limit, depending on the machine type. For a variety of reasons, 500 MB on disk can require much greater than 500 MB of RAM. In this particular case, as described above, downloading dependencies was using up RAM. This will not be the case for the approach described in the public docs.

**Comment by dizcology** [comment] 2021-01-08 22:05
@ToddMorrill: Looks like the more recent guidelines that @rhaertel80 provided should provide a working solution.  Closing this issue for now, but please feel free to reopen if you are still experiencing issues.

**Closed by dizcology** 2021-01-08 22:05 UTC
Labels: :rotating_light:, api: ml, priority: p2, type: question
