### ISSUE TITLE
unable to insert data in Big query using custom prediction routine 

### ISSUE THREAD

**Issue by rshah1990** [GoogleCloudPlatform/python-docs-samples#2627] opened 2019-12-17 14:56 UTC
When i am trying to insert a record in big query using from pandas.io import gbq , it throws some installation error. 

Code:

final_df.to_gbq(destination_table="dataset_logging.drift_detection",project_id="advance-vector-233712",if_exists='append')

**pandas-gbq requires google-cloud-bigquery: cannot import name 'collections_abc' from 'six.moves'**

![image](https://user-images.githubusercontent.com/37735152/71006418-52755700-210b-11ea-8429-bb2c0d78457d.png)

**Comment by tswast** [comment] 2019-12-17 17:45
This is a duplicate of https://github.com/googleapis/google-cloud-python/issues/9965. A fix was released in google-cloud-bigquery 1.23.1.

To fix, please upgrade your `google-cloud-bigquery` library and the `six` package.

```
pip install --upgrade six
```

**Comment by rshah1990** [comment] 2019-12-18 07:24
> This is a duplicate of [googleapis/google-cloud-python#9965](https://github.com/googleapis/google-cloud-python/issues/9965). A fix was released in google-cloud-bigquery 1.23.1.
> 
> To fix, please upgrade your `google-cloud-bigquery` library and the `six` package.
> 
> ```
> pip install --upgrade six
> ```

I have updated the package but its still not working.
my setup.py file:

**from setuptools import setup

REQUIRED_PACKAGES = ['sklearn','numpy','pandas','google-cloud-bigquery == 1.23.1','six == 1.13.0','pandas-gbq']

setup(
    name='my_custom_code',
    version='0.1',
    install_requires=REQUIRED_PACKAGES,
    scripts=['scikit-predictor.py'])**

Python Version: 3.5

Error:

![image](https://user-images.githubusercontent.com/37735152/71064619-85fcc380-2195-11ea-99ab-72070fc93552.png)

**Comment by tswast** [comment] 2019-12-18 15:45
Can you provide more of the ImportError traceback? It's not clear to me in which package the import is failing.

**Comment by rshah1990** [comment] 2019-12-18 17:01
I have uploaded sample code with setup file, I have also shared entire log file here , Please let me know in case you need more information.

[git.zip](https://github.com/GoogleCloudPlatform/python-docs-samples/files/3979576/git.zip)

**Comment by tswast** [comment] 2019-12-18 17:38
Gonzalo, can you investigate this problem with using BigQuery from AI Platform? I can't tell from the logs what might be causing this error.

**Comment by rshah1990** [comment] 2019-12-20 08:06
are you guys able to reproduce the issue ?
As mentioned in reference post that issue has been resolved , can you share the exact version of google-cloud-bigquery , six & pandas-gbq

**Comment by andrewferlitsch** [comment] 2020-03-17 21:43
@gogasca PTAL

**Comment by gogasca** [comment] 2020-04-20 15:17
We support Python 3.7. Can you please try it:
- Python 3.7
- google-cloud-bigquery 1.24.0
- pandas-gbq 0.13.1

**Comment by tbpg** [comment] 2020-05-11 13:11
We haven't heard back in a few weeks. So, I'm going to close this. But, feel free to comment or open another issue if you have trouble with another sample.

**Closed by tbpg** 2020-05-11 13:11 UTC
Labels: ML, bigquery, type: question
