### ISSUE TITLE
MediaTranslation hangs

### ISSUE THREAD

**Issue by Mozartt** [GoogleCloudPlatform/python-docs-samples#5885] opened 2021-05-25 08:07 UTC
I'm having issue running this file:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/media-translation/cloud-client/translate_from_file.py

python-docs-samples/media-translation/cloud-client/translate_from_file.py

I made two changes:
1. set credentials:
     credentials = service_account.Credentials.from_service_account_file('path_to_file.json')
      client = mediatranslation.SpeechTranslationServiceClient(credentials=credentials)

2. set the path to my audio file

I get no response from the server, only after 5 min hanging I get an timeout:
"The stream exceeded the 5-min"
Alghouth the stream is 6 seconds long.

when debugging the script i see 8  "mediatranslation.StreamingTranslateSpeechRequest" objects are generated in the "request_generator". And then it just hangs, no response is returning.

I've tried sending WAV file and then RAW-pcm file and it didnt helped.

**Comment by leahecole** [comment] 2021-05-27 16:43
Hey @telpirion I think this is in the translation space? If not and you know the right person to assign to, please pass it along

**Comment by munkhuushmgl** [comment] 2021-06-09 17:17
Hey  @Mozartt Could you share your installed packages?

```
python -m pip list 
```

**Comment by munkhuushmgl** [comment] 2021-06-09 17:20
What s  your target lang and source lang? 
what lang audio has?

**Comment by munkhuushmgl** [comment] 2021-06-09 17:23
With current version and  `.raw` audio file it is working as intended

![image](https://user-images.githubusercontent.com/45373284/121400599-03ca0700-c915-11eb-85ff-44137a2c6c37.png)

Maybe if you could share your audio file if thats not sensitive data.

**Comment by software-dov** [comment] 2021-06-17 23:16
The sample has a bug. In `StreamingTranslateSpeechRequest`, `streaming_config` and `audio_chunk` are part of the same `oneof`. It's a mistake to set both at the same time in the constructor, even to a null value.

I believe the fix is to change the `request_generator` to look like this

```python
def request_generator(config, audio_file_path):

        # The first request contains the configuration.
        yield mediatranslation.StreamingTranslateSpeechRequest(streaming_config=config)

        with open(audio_file_path, 'rb') as audio:
            while True:
                chunk = audio.read(4096)
                if not chunk:
                    break
                yield mediatranslation.StreamingTranslateSpeechRequest(audio_content=chunk)
```

Note in the first yield we only set `streaming_config` and in the second one only `audio_chunk`.

**Comment by michaeldebetaz** [comment] 2021-06-18 12:24
> The sample has a bug. In `StreamingTranslateSpeechRequest`, `streaming_config` and `audio_chunk` are part of the same `oneof`. It's a mistake to set both at the same time in the constructor, even to a null value.
> 
> I believe the fix is to change the `request_generator` to look like this
> 
> ```python
> def request_generator(config, audio_file_path):
> 
>         # The first request contains the configuration.
>         yield mediatranslation.StreamingTranslateSpeechRequest(streaming_config=config)
> 
>         with open(audio_file_path, 'rb') as audio:
>             while True:
>                 chunk = audio.read(4096)
>                 if not chunk:
>                     break
>                 yield mediatranslation.StreamingTranslateSpeechRequest(audio_content=chunk)
> ```
> 
> Note in the first yield we only set `streaming_config` and in the second one only `audio_chunk`.

Thank you so much for having given that! I'm new to GCP and I wanted to play with the Media Translation library, but I kept receiving 400 request errors without finding out why!

Now I can go to the next error: `source = result.recognition_result` get an attribution error :p

**Comment by software-dov** [comment] 2021-06-22 23:54
The API is still in beta, and things like this are unfortunately, frustratingly subject to change without warning.

**Closed** 2021-06-23 07:11 UTC
Labels: api: mediatranslation, samples, type: question
