### ISSUE TITLE
DLP Api throwing 404 The request concerns location 'us-east1' but was sent to location 'global'. Read go/storky-stubby for more information.

### ISSUE THREAD

**Issue by amitwats** [GoogleCloudPlatform/python-docs-samples#3005] opened 2020-02-28 00:22 UTC
## In which file did you encounter the issue?

/python-docs-samples/dlp/deid.py

### Did you change the file? If so, how?

The file was not changed

## Describe the issue
When I run the file the issue it throws is as below

> google.api_core.exceptions.NotFound: 404 Received the following error message from Cloud KMS when unwrapping KmsWrappedCryptoKey "projects/xxxxx/locations/us-east1/keyRings/dlp-test3/cryptoKeys/key7": The request concerns location 'us-east1' but was sent to location 'global'. Read go/storky-stubby for more information.

I do not mind creating the key in 'global' region but the issue is when I create a keyring in global I cannot make keys in HSM which is required to get the wrapped_key .
Cant see how to run this

**Comment by sethvargo** [comment] 2020-05-05 03:05
Dupe of https://github.com/googleapis/gapic-generator-python/issues/364?

**Comment by tmatsuo** [comment] 2020-05-15 17:51
@amitwats 

Thanks for the report. However, this sounds like an issue in the library. Please follow the issue in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3005#issuecomment-623809214

**Closed by tmatsuo** 2020-05-15 17:51 UTC
Labels: api: dlp, type: question
