### ISSUE TITLE
Image app sample throws error 500.

### ISSUE THREAD

**Issue by as1ndu** [GoogleCloudPlatform/python-docs-samples#151] opened 2015-12-21 22:20 UTC
Image app sample throws error 500 on signing in to guest book (local deploy)

**Comment by waprin** [comment] 2015-12-22 16:28
Thank you for the bug report, I have reproduced the issue, I am working on a fix now.

**Comment by waprin** [comment] 2015-12-22 19:51
@as1ndu Can you clarify a bit on the error? I originally had an error, but I have since installed PIL by doing
   sudo pip install pillow
and it fixed the issue. Let me know if something like that works for you. If that's the case we will update the docs.

**Comment by waprin** [comment] 2016-01-06 00:18
Closing due to lack of clarification, I will re-open if you can provide more info.

**Closed by waprin** 2016-01-06 00:18 UTC

**Comment by as1ndu** [comment] 2016-01-06 08:42
Pillow  installation does not solve the issue
