### ISSUE TITLE
RetryError using batch() on App Engine Flex

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/python-docs-samples#833] opened 2017-02-28 19:01 UTC
Hi,
I get the following exception using the batch() api on AppEngine Flex. 
```python
    batch = vision_client.batch()
    for blob in blobs:
            content = blob.download_as_string()
            image = vision_client.image(content=content)
            batch.add_image(image, FEATURES)
    results = batch.detect()
``` 
DEBUG:google_auth_httplib2:Making request: POST https://accounts.google.com/o/oauth2/token
ERROR:root:Exception occurred in retry method that was not classified as transient
<class 'google.gax.errors.RetryError'>

Package:
google-cloud-vision (0.23.2)

**Comment by jonparrott** [comment] 2017-02-28 20:22
@sprakash3 do you have any other logs? The RetryError seems to be obscuring the real error.

/cc @lukesneeringer

**Comment by lukesneeringer** [comment] 2017-02-28 22:05
I will look into changing this to raise the _actual_ error.

**Comment by sprakash3** [comment] 2017-02-28 22:56
@jonparrott @lukesneeringer Some of the images in the batch request exceeded the resource limit for the vision api. I'll have to figure out a way to get around them.
Thanks

**Comment by daspecster** [comment] 2017-02-28 23:03
@sprakash3 do you have an example so I could reproduce the same error that you were getting?

**Comment by sprakash3** [comment] 2017-02-28 23:14
@daspecster Any image greater than 4 MB in size would result in this error. I'm sorry i cant share the image.

**Comment by daspecster** [comment] 2017-02-28 23:39
Thanks @sprakash3! That information is what I needed.

**Comment by engelke** [comment] 2018-12-07 23:45
Closing this issue as dealt with above.

**Closed by engelke** 2018-12-07 23:45 UTC
Labels: Fixit, ML
