### ISSUE TITLE
Deadline Exceeded Exception with Streaming ASR Example

### ISSUE THREAD

**Issue by alexanderepstein** [GoogleCloudPlatform/python-docs-samples#2578] opened 2019-11-26 23:52 UTC
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/microphone/transcribe_streaming_mic.py

### Did you change the file? If so, how?
No

## Describe the issue

```
Traceback (most recent call last):
  File "/Users/epstea/.local/share/virtualenvs/projectname-PwV2T-lT/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "/Users/epstea/.local/share/virtualenvs/projectname-PwV2T-lT/lib/python3.7/site-packages/grpc/_channel.py", line 392, in __next__
    return self._next()
  File "/Users/epstea/.local/share/virtualenvs/projectname-PwV2T-lT/lib/python3.7/site-packages/grpc/_channel.py", line 561, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1574812008.659742000","description":"Error received from peer ipv4:216.58.193.74:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/unix/workplace/projectnameSpace/projectname/test.py", line 185, in <module>
    main()
  File "/Volumes/unix/workplace/projectnameSpace/projectname/test.py", line 181, in main
    listen_print_loop(responses)
  File "/Volumes/unix/workplace/projectnameSpace/projectname/test.py", line 120, in listen_print_loop
    for response in responses:
  File "/Users/epstea/.local/share/virtualenvs/projectname-PwV2T-lT/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

This was previously working for me and now I am constantly seeing this exception after about 15 seconds. I only started seeing this issue after I did an upgrade of my pipenv.

This is the current environment (from pip freeze)

```
alabaster==0.7.12
Babel==2.7.0
cachetools==3.1.1
certifi==2019.9.11
chardet==3.0.4
Click==7.0
cycler==0.10.0
docopt==0.6.2
docutils==0.15.2
Flask==1.1.1
google-api-core==1.14.3
google-auth==1.7.1
google-cloud-speech==1.3.0
googleapis-common-protos==1.6.0
grip==4.5.2
grpcio==1.25.0
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.3
joblib==0.14.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
numpy==1.17.4
packaging==19.2
pandas==0.25.3
path-and-address==2.0.1
protobuf==3.11.0
psrecord==1.1
psutil==5.6.6
pyasn1==0.4.8
pyasn1-modules==0.2.7
PyAudio==0.2.11
pycryptodomex==3.9.4
Pygments==2.4.2
pyparsing==2.4.5
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
rsa==4.0
six==1.13.0
snowballstemmer==2.0.0
urllib3==1.25.7
Werkzeug==0.16.0
```

Is this caused by my recent upgrade? If so what can I do to downgrade back to a working version?

**Comment by kurtisvg** [comment] 2019-11-27 02:58
@alexanderepstein - You should be able to install a specific version into your pip-env with `pipenv install google-cloud-speech==1.2.0` or whatever version you prefer to run. 

@nnegrey - Can you take a look at this?

**Comment by alexanderepstein** [comment] 2019-11-27 03:14
@kurtisvg sorry I should have been more clear, I know how to downgrade I meant more so what version should I downgrade to if the error is truly caused by me upgrading. Thanks for the quick response I do appreciate it

**Comment by kurtisvg** [comment] 2019-11-27 15:59
@alexanderepstein - My best guess would be to check the requirements.txt for that sample (which looks like it's `google-cloud-speech==1.2.0`).

**Comment by alexanderepstein** [comment] 2019-11-27 16:17
Thank you @kurtisvg downgrading fixed my issue! I would like to be able to upgrade again when this gets sorted out, but in the meantime this is fine with me.

**Comment by nnegrey** [comment] 2019-11-27 16:45
I'll start looking at this and try to get to 1.3.0 working.

**Comment by nnegrey** [comment] 2019-11-27 17:13
@busunkim96, is this have anything to do with recent library changes?
Speech being now idempotent? https://github.com/googleapis/google-cloud-python/pull/9292

I'm able to reproduce by either not speaking into the mic or by speaking into the mic, I know something got turned into idempotent. 

Some issues I found that seem to be related, the 2nd related to an idempotent issue. 
https://github.com/googleapis/google-cloud-python/issues/8933
https://github.com/googleapis/google-cloud-python/issues/9390

**Comment by busunkim96** [comment] 2019-12-02 22:30
@nnegrey I'm not sure. Can you try changing the [config](https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1/gapic/speech_client_config.py) locally and seeing if that resolves the error? Have you seen reports of this in other languages?

FWIW it doesn't look like the configs for StreamingRecognize or LongRunningRecognize have changed recently (they're  both `non_idempotent`).

**Comment by nnegrey** [comment] 2019-12-02 22:32
It looks like that change happened awhile ago, but this was the first release to pick it up. 

I'll try messing with the config locally.

**Comment by nnegrey** [comment] 2019-12-02 23:02
@busunkim96, it actually appears to have to do with the timeouts. 

https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1/gapic/speech_client_config.py#L13-L15

Bumping `initial_rpc_timeout_millis` and `max_rpc_timeout_millis` to `300000` or 5 minutes (I believe the current limit, then it seems to go away)

**Comment by busunkim96** [comment] 2019-12-02 23:56
The client config is generated off of `speech_grpc_service_config.json`, which lives by the protos. Can you take a look at the config and send a CL with adjustments ?

googleapis/google/cloud/speech/v1/speech_grpc_service_config.json

**Comment by busunkim96** [comment] 2019-12-05 21:07
Fix has been made to `speech_gapic.yaml`. There should be a synth PR to google-cloud-python tomorrow with the fix

**Comment by onofrioP89** [comment] 2019-12-17 14:35
With `google-cloud-speech==1.2.0` the problem is not showed also using v1p1Beta1
With `google-cloud-speech==1.3.1` the error 504 is received

**Comment by nnegrey** [comment] 2019-12-17 16:47
Looks like only v1 got the fix:
https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1/gapic/speech_client_config.py#L10-L16

v1p1beta1 is still on the old timeout:
https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1p1beta1/gapic/speech_client_config.py#L10-L16

**Comment by busunkim96** [comment] 2019-12-17 17:14
@nnegrey Ah I didn't realize it was a problem in both. Can you send a CL that makes the same changes to v1p1beta1?

**Comment by nnegrey** [comment] 2019-12-17 17:16
Yep, already done.

**Comment by nnegrey** [comment] 2020-01-06 20:18
Going to close as it looks like these changes have been pushed out.

**Closed by nnegrey** 2020-01-06 20:18 UTC
Labels: type: question
